(require 'package)
(add-to-list 'package-archives '("melpa-stable" . "http://melpa-stable.milkbox.net/packages/") t)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)

(setq my-packages '(paredit clojure-mode cider web-mode
			    scss-mode exec-path-from-shell nodejs-repl
			    inf-ruby feature-mode slime yafolding
			    yaml-mode coffee-mode nginx-mode wrap-region
			    org markdown-mode sml-mode haml-mode magit
			    projectile rspec-mode htmlize ob-cypher
			    ob-browser ob-http rinari circe))

(defun packages-missing-p (packages)
  (let ((package-missing-p nil))
    (while (and (not package-missing-p) packages)
      (if (package-installed-p (car packages))
	(setq packages (cdr packages))
	(setq package-missing-p t)))
    package-missing-p))

(if (packages-missing-p my-packages)
  (progn
    (package-refresh-contents)
    (dolist (p my-packages)
      (if (not (package-installed-p p))
	  (package-install p)))))


;; Get path from .bashrc instead of the GUI that launched Emacs
(exec-path-from-shell-initialize)


;; UI Customization
(setq inhibit-startup-screen -1)
(tool-bar-mode -1)
(menu-bar-mode -1)
(show-paren-mode)
(require 'ido)
(ido-mode t)
(load-theme 'deeper-blue)

;; Shift keys for window navigation
(windmove-default-keybindings)

;; Keep backup files in a global location instead of local dir
(setq backup-directory-alist `(("." . "~/.backup")))
(setq backup-by-copying t)


;; Projectile
(projectile-global-mode)


;; Elisp
(add-hook 'emacs-lisp-mode-hook 'paredit-mode)
(add-hook 'emacs-lisp-mode-hook 'yafolding-mode)


;; Clojure
(require 'clojure-mode)

(add-hook 'clojure-mode-hook 'paredit-mode)
(add-hook 'clojure-mode-hook 'yafolding-mode)
(define-key clojure-mode-map (kbd "C-o j") 'cider-jack-in)
(define-key clojure-mode-map (kbd "C-o J") 'cider-restart)

(defun clojure-indent (syms indent)
  (mapcar (lambda (sym) (put-clojure-indent sym indent)) syms))

;; Cucumber Indents for Clojure features
(setq cucumber-indents '(Given When Then And But))
(clojure-indent cucumber-indents 2)

;; Compojure Indents
(setq compojure-indents '(context GET POST))
(clojure-indent compojure-indents 2)


;; Cider
(add-hook 'cider-repl-mode-hook 'paredit-mode)


;; Web-mode
(add-hook 'web-mode-hook 'yafolding-mode)
(add-to-list 'auto-mode-alist '("\\.html$" . web-mode)) ; override the default html-mode
(add-to-list 'auto-mode-alist '("\\.html.erb$" . web-mode))
(setq web-mode-markup-indent-offset 2)
(setq web-mode-css-indent-offset 2)
(setq web-mode-code-indent-offset 2)

;; By default, web-mode uses comment-dwim to autocomment. However,
;; the org-mode tangle function attempts to use the comment-start and
;; comment-end variables to insert sourcemap comments, so we must
;; specify them manually.
(add-hook 'web-mode-hook
	  (lambda () (progn
		       (setq comment-start "<!--")
		       (setq comment-end "-->"))))


;; Ruby
(add-hook 'ruby-mode-hook 'yafolding-mode)
(add-to-list 'auto-mode-alist '("\\.rake$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\Vagrantfile$" . ruby-mode))


;; Javascript
(setq js-indent-level 2)
(add-hook 'javascript-mode-hook 'yafolding-mode)
(add-to-list 'interpreter-mode-alist '("node" . javascript-mode))


;; SASS
(setq scss-compile-at-save nil)


;; CSS
(setq css-indent-offset 2)


;; nginx
(add-to-list 'auto-mode-alist '("\\nginx.conf$" . nginx-mode))


;; Org

;; Force org-mode to load. We wwant this key available from files
;; that were generated by org before the original org file is opened.
(require 'org)

(setq org-src-fontify-natively t)

;; Useful global orgmode functions
(global-set-key "\C-cl" ’org-store-link)
(global-set-key "\C-cc" ’org-capture)
(global-set-key "\C-ca" ’org-agenda)
(global-set-key "\C-cb" ’org-iswitchb)
(global-set-key (kbd "C-c j") 'org-babel-tangle-jump-to-org)

;; Try and fix the issue where editing an org-mode code block
;; sets all of my indents to 8
(add-hook 'org-mode-hook (lambda ()
			   (progn
			     (setq web-mode-markup-indent-offset 2)
			     (setq web-mode-css-indent-offset 2)
			     (setq web-mode-code-indent-offset 2))))


;; When editing Clojure code you often want to see both the REPL and
;; the code. However, org-mode's default behavior when editing a code
;; block is to reorganize the frame so that only the org file and your
;; code block are visible. Lets reconfigure this
(setq org-src-window-setup 'other-window)

